### ISSUE TITLE
complain about 'cannot locate Gemfile'.

### ISSUE THREAD

**Issue by aleiphoenix** [syohex/emacs-realtime-markdown-viewer#1]
I'm using emacs 24.3 in daemon mode with prelude on a Gentoo Linux box.

When I open a markdown file outside the realtime viewer source code directory and try to run `M-x realtime-markdown-viewer-mode`, it complained about 'cannot locate Gemfile'. (BTW, I've set `rtmv:lang` to `ruby` :) )

My guess is the `load-file-name` is `nil` and `default-directory` of `start-process-shell-command` should be set.

`load-file-name` is only accessible when the `*.el` is being loaded, right ?

and I tried to define a variable 

```elisp
(defvar rtmv:module-path (file-name-directory load-file-name))
```

and tweak a little.

```elisp
(defun rtmv:webapp-launch (port)
  (let ((cmd (rtmv:webapp-launch-command port))
        (default-directory rtmv:module-path)) ;; added this line
    (setq rtmv:webapp-process
          (start-process-shell-command "rtmv" "*realtime markdown*" cmd)))
```

this works for me, I could now run `M-x realtime-markdown-viewer-mode` anywhere , on any file. 

Could you check this out ?

Thanks.

**Comment by jasonm23** [comment]
(Looks like this is closed :) )
